blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question / discussion
    url: https://github.com/WORLD-DOMINATION-SOFTWARE/<repo>/discussions
    about: "For Q&A and open-ended topics"
